### ISSUE TITLE
Finishing the first Milestone for this Kanban project - Alexander

### ISSUE THREAD

**Issue by alexander16108** [alexander16108/SpaceShip-Travels#38]
Hi, There fellow Micronaut 👋🏾 

Just wanted to inform you that we are official two working on the capstone project together, and we have met all the requirement for this project to be approved

cheers 🥂 and Happy Monday 🧑‍💼 

Alexander

**Comment by mikenath223** [comment]
Hello Team,

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._
- [ ] As stated in the requirement, your project board should be a copy of [this template board](https://github.com/microverseinc/curriculum-javascript/projects/1) since you are a team of 2 you shouldn't exceed more than 15 cards on the project board. Kindly fix it.
- [ ] Also you failed to assign cards to a team member, each card should be assigned to a team member, but for group tasks, you have the option to assign them to both of you or a single team member. Check the [project requirement here](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20of%20the%20team%20members%20should%20assign%20themselves%20to%20the%20correct%20cards.%20Decide%20who%20will%20be%20the%20assignee%20for%20the%20cards%20marked%20as%20group%20tasks.%20All%20cards%20on%20your%20Kanban%20board%20should%20have%20assignees.) and [see screenshot](https://gitlab.com/microverse/guides/tse/code_review/code_review_guidelines_2_0/-/raw/master/javascript/group-capstone/assigned_card.png).

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alexander16108** [comment]
@mikenath223,
But I already said we are of two members in the team and from the requirement we need to remove the task which is meant to be assigned to the third team member

**Comment by mikenath223** [comment]
Hi there, 

Awesome job on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. Let's work on those.


 ## Required Changes ♻️
_Kindly check the comments under the review._
- [ ] As stated in the previous review kindly ensure that **each card is assigned to a team member**. Please refer to [this line](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=All%20cards%20on%20your%20Kanban%20board%20should%20have%20assignees.) on the project guide.

Happy coding, Cheers!🚀🚀

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it's valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vichuge** [comment]
# Required Changes ♻️ ♻️ ⚠️ ⚠️ 🚦 🚦 

Hi dear student, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![star_wars_almost_there](https://user-images.githubusercontent.com/20563252/121369354-644f4900-c901-11eb-9844-50c85d0f206b.gif)


## Aspects to improve ♻️
_Check the comments under the review._

- [ ] As the last review said, check if all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
![image](https://user-images.githubusercontent.com/20563252/128746631-342f7d91-82db-48e8-a274-a8121c62e693.png)

- At this point, it looks like your tasks are not assigned yet. Please work on it.
![image](https://user-images.githubusercontent.com/20563252/128746731-a74ca08a-a498-476d-96a3-a7f842e3062b.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alexander16108** [comment]
hi @vichuge,
my coding partner has requested leave for personal reasons and Is not available to accept any invites for collaboration or assignment of tasks

**Comment by alexander16108** [comment]
@vichuge , please what do i do in this case

**Comment by SpaYco** [comment]
Hello 👋,

_This is an additional review as a result of the second opinion request._

I believe you currently have no other person to work with? Please send a Zendesk ticket through the dashboard, so student success can fix this issue for you, if it's another problem, let me know

Keep rocking 🚀!

**Comment by Temmarie** [comment]
Hello  @alexander16108  :wave: 

_This is an additional review as a result of the second opinion request._

You complained about your project not being completed due to your partner's absence and thus has not been approved. Since you've been given the go-ahead by Anne, I will inform the necessary people so the last review will be cancelled and your project can be approved.  

Keep rocking :rocket:!
